In [1]:
import tensorflow as tf

In [2]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 8s 1us/step


In [10]:
# 60000 (28*28)images
x_train.shape

(60000, 28, 28)

In [13]:
# First image
x_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.10677171,  1.1955873 , -0.5663919 ,  0.13605523,  0.43644127,
         0.44658   , -0.30523196,  0.39046073,  0.26893768, -0.44377   ]],
      dtype=float32)

In [18]:
tf.nn.softmax(predictions).numpy()

array([[0.0681244 , 0.25055903, 0.04302217, 0.08684827, 0.11727816,
        0.11847326, 0.05586149, 0.11200774, 0.09919077, 0.0486347 ]],
      dtype=float32)

In [20]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn

In [21]:
loss_fn(y_train[:1], predictions).numpy()

2.133068

In [22]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


1875/1875 [==============================] - 4s 2ms/step - loss: 0.2898 - accuracy: 0.9161
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1430 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1069 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0867 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0767 - accuracy: 0.9762


In [27]:
model.evaluate(x_test,  y_test)


313/313 [==============================] - 0s 943us/step - loss: 0.0765 - accuracy: 0.9767


[0.07653650641441345, 0.9767000079154968]

In [31]:
# Provides more detailed output during evaluation.
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0765 - accuracy: 0.9767 - 312ms/epoch - 996us/step


[0.07653650641441345, 0.9767000079154968]

In [33]:
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [34]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.20085852e-09, 6.39731690e-09, 2.57061970e-07, 9.01426902e-05,
        3.17070914e-13, 1.07616643e-07, 1.22851245e-14, 9.99909043e-01,
        1.80097681e-09, 5.00893350e-07],
       [3.38489023e-08, 1.89956936e-05, 9.99980450e-01, 5.09580047e-07,
        2.14275265e-17, 2.29741044e-08, 2.44986542e-09, 1.80423851e-12,
        1.96730703e-08, 4.52777523e-15],
       [2.64002210e-07, 9.99345124e-01, 2.82298406e-05, 3.98074781e-06,
        2.28322479e-05, 2.47783264e-05, 1.06750913e-05, 3.37667123e-04,
        2.26089673e-04, 3.76492437e-07],
       [9.99490142e-01, 6.43271603e-10, 9.63725179e-05, 2.84673462e-07,
        1.01361593e-06, 4.65585708e-06, 3.76163407e-05, 3.63832252e-04,
        1.23441552e-07, 5.84120744e-06],
       [1.20386414e-06, 1.79280213e-09, 2.78972493e-06, 5.34807576e-08,
        9.97915804e-01, 8.59316515e-07, 8.69033465e-06, 5.74136793e-05,
        2.06016566e-07, 2.01287819e-03]], dtype=float32)>